In [2]:
x = 10
print(x)

10


In [3]:
x + 1

11

In [4]:
x / 2

5.0

# Modulul numpy

In [5]:
import numpy as np

In [6]:
np.__version__

'2.0.2'

In [7]:
!pip install numpy

In [9]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

# Python este loosly typed

In [12]:
x = 10
x, type(x)

(10, int)

In [13]:
x = True
x, type(x)

(True, bool)

In [14]:
x = [ 30, 40, 50, 60 ]
x, type(x)

([30, 40, 50, 60], list)

In [15]:
x = [ 30, 40, 50, 60, "hello", 30.3 ]
x, type(x)

([30, 40, 50, 60, 'hello', 30.3], list)

## NP Array vs List
# array - omogen
# lista - heterogena

In [17]:
x = np.array([ 30, 40, 50, 60 ])
x, type(x), x.dtype

(array([30, 40, 50, 60]), numpy.ndarray, dtype('int64'))

In [18]:
x = np.array([ 30, 40, 50, 60 ], dtype = np.int8)
x, type(x), x.dtype

(array([30, 40, 50, 60], dtype=int8), numpy.ndarray, dtype('int8'))

# Reprezentarea numerelor in binar

In [19]:
bin(0)

'0b0'

In [20]:
bin(1)

'0b1'

In [21]:
bin(2)

'0b10'

In [22]:
for i in range(10):
  print(i, " bin ", bin(i))

0  bin  0b0
1  bin  0b1
2  bin  0b10
3  bin  0b11
4  bin  0b100
5  bin  0b101
6  bin  0b110
7  bin  0b111
8  bin  0b1000
9  bin  0b1001


In [23]:
bin(2 ** 8)

'0b100000000'

In [24]:
bin(2 ** 8 - 1)

'0b11111111'

In [27]:
2 ** 8 - 1

255

# Uint8 - de la 0 la 255

In [29]:
x = np.array([ 30, 40, 50, 60, 255 ], dtype = np.uint8)
x

array([ 30,  40,  50,  60, 255], dtype=uint8)

Int8 - de la -128 la 127

In [31]:
x = np.array([ 30, 40, 50, 60, 127 ], dtype = np.int8)
x

array([ 30,  40,  50,  60, 127], dtype=int8)

In [33]:
x = np.array([ 30, 40, 50, 60, -128 ], dtype = np.int8)

In [34]:


x = np.array([ 30, 40, 50, 60, 127 ])
x, type(x), x.dtype

(array([ 30,  40,  50,  60, 127]), numpy.ndarray, dtype('int64'))

In [35]:
x = np.array([ 30, 40, 50, 60, 127.3 ])
x, type(x), x.dtype

(array([ 30. ,  40. ,  50. ,  60. , 127.3]), numpy.ndarray, dtype('float64'))

In [36]:
x = np.array([ 30, 40, 50, 60, 127.3, "salutare"])
x, type(x), x.dtype

(array(['30', '40', '50', '60', '127.3', 'salutare'], dtype='<U32'),
 numpy.ndarray,
 dtype('<U32'))

In [37]:
x = np.array([ 30, 40, 50, 60, 127.3, "salutare", True])
x, type(x), x.dtype

(array(['30', '40', '50', '60', '127.3', 'salutare', 'True'], dtype='<U32'),
 numpy.ndarray,
 dtype('<U32'))

In [40]:
# lista clasica
x = [ 30, 40, 50, 60, 127.3, "salutare", True]
x

[30, 40, 50, 60, 127.3, 'salutare', True]

In [41]:
x[0], type(x[0])

(30, int)

In [42]:
x[-1], type(x[-1])

(True, bool)

In [43]:
x[-2], type(x[-2])

('salutare', str)

In [44]:
x = [ 30, 40, 50, 60, 127.3, "salutare", True, [56, 32]]
x

[30, 40, 50, 60, 127.3, 'salutare', True, [56, 32]]

# Homogeneous - > aceeasi forma

In [48]:
x = np.array([ [30, 40, 50], [60, 127.3, "salutare"], [True, 56, 32]])
x

array([['30', '40', '50'],
       ['60', '127.3', 'salutare'],
       ['True', '56', '32']], dtype='<U32')

In [49]:
type(x), x.dtype, x.shape

(numpy.ndarray, dtype('<U32'), (3, 3))

In [50]:
x = np.array([ [30, 40, 50], [60, 127.3, "salutare"]])
x

array([['30', '40', '50'],
       ['60', '127.3', 'salutare']], dtype='<U32')

In [51]:
type(x), x.dtype, x.shape

(numpy.ndarray, dtype('<U32'), (2, 3))

# Fast mathematical operations

In [54]:
list_x = [10, 20, 30, 40]

In [55]:
for i in list_x:
  print(i)

10
20
30
40


In [57]:
noua_lista = []
for i in list_x:
  noua_lista.append(i + 3)
noua_lista

[13, 23, 33, 43]

In [58]:
np_array_x = np.array([10, 20, 30, 40])
np_array_x

array([10, 20, 30, 40])

In [59]:
np_array_x + 3

array([13, 23, 33, 43])

In [60]:
np_array_x + np_array_x

array([20, 40, 60, 80])

In [61]:
np_array_x - np_array_x

array([0, 0, 0, 0])

In [62]:
np_array_x * np_array_x

array([ 100,  400,  900, 1600])

In [63]:
np_array_x * 2

array([20, 40, 60, 80])

In [64]:
np_array_x ** 2

array([ 100,  400,  900, 1600])

# Generare de numere

In [65]:
for i in range(10):
  print("i=", i)

i= 0
i= 1
i= 2
i= 3
i= 4
i= 5
i= 6
i= 7
i= 8
i= 9


In [66]:
range(10)

range(0, 10)

In [68]:
for i in range(3, 7):
  print("i=", i)

i= 3
i= 4
i= 5
i= 6


In [69]:
list(range(3, 7))

[3, 4, 5, 6]

In [70]:
np.array(range(3, 7))

array([3, 4, 5, 6])

# Exista functia arange

In [71]:
np.arange(3, 7)

array([3, 4, 5, 6])

In [72]:
np.array(range(3, 7))

array([3, 4, 5, 6])

In [73]:
np.arange(30, 70)

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

In [74]:
np.arange(30, 70, 5)

array([30, 35, 40, 45, 50, 55, 60, 65])

In [75]:
np.arange(30, 71, 5)

array([30, 35, 40, 45, 50, 55, 60, 65, 70])

In [76]:
np.arange(30, 71, 5, dtype = np.float32)

array([30., 35., 40., 45., 50., 55., 60., 65., 70.], dtype=float32)

In [77]:
np.arange(30, 71, 5).reshape(3, 3)

array([[30, 35, 40],
       [45, 50, 55],
       [60, 65, 70]])