In [ ]:
import tensorflow as tf

In [34]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
tf.__version__

'2.19.0'

In [ ]:
print(tf.__doc__)


Top-level module of TensorFlow. By convention, we refer to this module as
`tf` instead of `tensorflow`, following the common practice of importing
TensorFlow via the command `import tensorflow as tf`.

The primary function of this module is to import all of the public TensorFlow
interfaces into a single place. The interfaces themselves are located in
sub-modules, as described below.

Note that the file `__init__.py` in the TensorFlow source code tree is actually
only a placeholder to enable test cases to run. The TensorFlow build replaces
this file with a file generated from [`api_template.__init__.py`](https://www.github.com/tensorflow/tensorflow/blob/master/tensorflow/api_template.__init__.py)



# Tensor -> echivalentul unui array (numpy)

In [7]:
scalar = tf.constant(3) # echivalentul unei constante
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [6]:
scalar.ndim

0

In [8]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
vector.ndim

1

In [12]:
vector.numpy(), type(vector.numpy())

(array([10, 10], dtype=int32), numpy.ndarray)

In [13]:
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [14]:
matrix.ndim

2

In [16]:
matrix = tf.constant([[10, 7.3],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10. ,  7.3],
       [ 7. , 10. ]], dtype=float32)>

# Creare de tensori variabili

In [18]:
variable = tf.Variable([10, 10])
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>

In [19]:
constanta = tf.constant([10, 10])
constanta

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

# In Python nu exista idee de constant - by default

In [20]:
PI = 3.14

In [21]:
import math

In [22]:
math.pi

3.141592653589793

In [23]:
math.pi  = 3.15

In [24]:
math.pi

3.15

In [25]:
constanta[0] = 1003

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

In [26]:
variable[0] = 3231

TypeError: 'ResourceVariable' object does not support item assignment

Editarea se face prin functii

In [27]:
variable[0].assign(77777)
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([77777,    10], dtype=int32)>

In [28]:
constanta[0].assign(77777)
constanta

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

# Generare de tensori random

In [32]:
random_tensor = tf.random.Generator.from_seed(3)


In [33]:
random_tensor.normal(shape=(3, 2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.43640924, -1.9633987 ],
       [-0.06452483, -1.056841  ],
       [ 1.0019137 ,  0.6735137 ]], dtype=float32)>

In [35]:
np.random.normal(size=(3, 2))

array([[ 0.18960958,  0.79997747],
       [-0.32046562,  0.43242826],
       [-1.12788741, -0.72737794]])

 # Alte forme de generare de tensori

In [36]:
tf.ones(shape=10)

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>

In [37]:
np.ones(shape=10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Creare cu ajutor numpy

In [38]:
tensor_from_numpy = tf.constant(np.array([10, 10]))
tensor_from_numpy

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([10, 10])>

In [39]:
tensor_from_numpy = tf.Variable(np.array([10, 10]))
tensor_from_numpy

<tf.Variable 'Variable:0' shape=(2,) dtype=int64, numpy=array([10, 10])>

In [40]:
tensor_from_numpy + 2

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([12, 12])>

In [42]:
twnety_ones = tf.ones(20) * 2.1
twnety_ones

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1,
       2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1], dtype=float32)>

In [45]:
# twnety_ones.reshape(5, 4)

tf.reshape(twnety_ones, shape=(5, 4))

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1],
       [2.1, 2.1, 2.1, 2.1]], dtype=float32)>